name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
        PPLX_API_KEY: ${{ secrets.PPLX_API_KEY }}
      run: npm run build 